### ISSUE TITLE
iOS - Not working

### ISSUE THREAD

**Issue by longde123** [stevefsp/critterai#27]
cai-nav-rcn compiles without problems.

 However Unity fails to a iOS run time

 worse still there isn't a helpful error message

**Comment by KellanHiggins** [comment]
What is the error message?

**Comment by longde123** [comment]
at 
dt nav mesh 
line 783

addTile
getTileAt

empty ptr

**Comment by longde123** [comment]
line 794

**Comment by KellanHiggins** [comment]
That looks like you haven't set up a tile that is being referenced in the C++ part of the program. But it works fine on a PC build?

**Comment by longde123** [comment]
it work 
when  link  it as  static lib  .a  thank you

**Comment by stevefsp** [comment]
Looks like this is resolved.  If not, let me know and I'll reopen.
